CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_BACKEND_RTT=n
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y

# ESB radio link
CONFIG_ESB=y
CONFIG_CLOCK_CONTROL=y
CONFIG_ESB_CLOCK_INIT=y
CONFIG_ESB_RADIO_IRQ_PRIORITY=0
CONFIG_ESB_PIPE_COUNT=8

# Platform
CONFIG_CONSOLE=y
CONFIG_GPIO=y
CONFIG_PINCTRL=y
CONFIG_FLASH=y
CONFIG_SYSTEM_CLOCK_WAIT_FOR_STABILITY=y
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_BUILD_OUTPUT_UF2=n

# Initialize the composite device from main after registering HID.
CONFIG_BOARD_SERIAL_BACKEND_CDC_ACM=n
CONFIG_USB_CDC_ACM=y

# Legacy USB device stack, composite HID keyboard + CDC debug serial
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n
CONFIG_USB_COMPOSITE_DEVICE=y
CONFIG_USB_DEVICE_HID=y
CONFIG_USB_DEVICE_VID=0x1B4F
CONFIG_USB_DEVICE_PID=0x0001
CONFIG_USB_DEVICE_PRODUCT="A4TECH Receiver"
CONFIG_USB_DEVICE_MANUFACTURER="Monard"
CONFIG_USB_HID_POLL_INTERVAL_MS=1
CONFIG_USB_HID_BOOT_PROTOCOL=y
CONFIG_USB_DEVICE_OS_DESC=y
